spring:
  datasource:
    url: jdbc:postgresql://postgresqldb:5432/db_enefit
    username: postgres
    password: energypass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    liquibase-schema: public
    default-schema: public
    enabled: true

logging:
  level:
    liquibase: DEBUG
    org.springframework: INFO

server:
  port: 9093

market-price:
  base-url: https://estfeed.elering.ee/api/public/v1
  price-url: /energy-price/electricity
